### ISSUE TITLE
keeps taking me back to "connect your space" infinite loop after I already set it up

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/openarchive-ios#106] opened 2019-05-08 21:04 UTC
@tladesignz
Test Flight version 19
Phone: iphone xr ios 12.2 on wifi only

After adding server info, connecting to projects on server and adding media to one project, I went to add a third project and it took me back to the connect your space screen. I can't get out of it or "skip".

 When I re-added info. it let me browse files again but when I selected one, it took me back to connect your space screen.

**Comment by tladesignz** [comment] 2019-05-09 08:38
Sorry, I can't reproduce that. Not with these instructions.
Please provide more details:
- What exactly did you do? List *every* step, including stuff like leaving the app, switching things on and off like WiFi, *in the exact order you did it*.
- Which server(s) did you use?
- What kind of items did you add?
- How did you add them? Share extension vs. gallery import.

**Comment by tladesignz** [comment] 2019-05-22 19:32
Ah, this is duplicated in #111. Fixed in the meantime.

**Closed by tladesignz** 2019-05-22 19:32 UTC
Labels: bug
