### ISSUE TITLE
Locations are incorrect on iPhone 8

### ISSUE THREAD

**Issue by kckthx** [OpenArchive/openarchive-ios#137] opened 2019-07-16 15:22 UTC
I uploaded images to an existing project on the gp cloud server and its saying the location was Tibet, even though I took the photos in Bryan, TX and uploaded them in Lubbock.

![IMG_3706](https://user-images.githubusercontent.com/36669955/61306067-8c83ab00-a7b1-11e9-8a2e-e43b447fef62.PNG)

I'm not connected to a vpn, but we have noticed that our IP address on our wifi says it's somewhere else just in general. So I turned off wifi and uploaded pics again and they still said China.
![IMG_3707](https://user-images.githubusercontent.com/36669955/61306259-e5534380-a7b1-11e9-93b5-d46f4b5545c8.PNG)

I tried to reproduce on the iPhone 6 while it was connected to wifi and it had the correct location
![IMG_0692](https://user-images.githubusercontent.com/36669955/61307168-7971da80-a7b3-11e9-9818-244f5f26c047.PNG)

**Comment by tladesignz** [comment] 2019-07-18 13:05
The algorithm reads coordinates from EXIF information attached inside the photo file and sends that to Apple's geocoding service which gives us an address. So, in theory, that service could have fucked up.

Another explanation would be, that you batch-edited the photos together with an image, which *was* shot there, and unknowingly set the location of all photos in the batch to that.

Of course, the coordinates in the photo could have been set to that coordinates with something else.

Can you do the following?

- Check what Apple's Photos app shows as location.
- Check, if there was a file in the batch, which is from there.

Thanks!

**Comment by kckthx** [comment] 2019-07-18 13:50
@tladesignz I've not been to china in 7 years, and definitely not with this phone or to Tibet ever. 
How do I check what it's tracking my location as? I can only see that I have location turned on.

**Comment by tladesignz** [comment] 2019-07-18 13:59
As said, the location is stored inside the image file. If you imported an image from somewhere, that can have a location where you have never been.

Look at photos in the "Photos" app. Scroll down to see a map with a mark of the images location.

**Comment by kckthx** [comment] 2019-07-18 14:11
Oh, right! Yeah these were all taken on my phone. Not uploaded to it. when I scroll down it shows the location being at the hospital it was taken at. 

![IMG_50F8CA4E55B8-1](https://user-images.githubusercontent.com/36669955/61464504-f760ed80-a93b-11e9-8425-53ef0b1e3cc5.jpeg)

**Comment by tladesignz** [comment] 2019-07-18 19:58
Puuh, ok. Don't have a clue, sorry.

Please try to reproduce the problem, and tell me exactly how to do it! Needs to be a clear list of photos and a description of what you did in what order. Thanks!

**Comment by n8fr8** [comment] 2019-07-29 17:37
@tladesignz can she provide that image to you to try and reproduce?

**Comment by n8fr8** [comment] 2019-07-29 17:39
or perhaps @purvi-ranawat can help reproduce or look for similar issues.

**Comment by foundscapes** [comment] 2019-07-29 18:23
Collin and I have been unable to reproduce this, would love it if @purvi-ranawat could try too

**Comment by purvi-ranawat** [comment] 2019-07-30 01:42
I have tried on Iphone XR - IOS 12.3 and it is also working fine for me. Correct location of the photo uploaded is getting displayed.

Below is the screenshot :

![location](https://user-images.githubusercontent.com/8190141/62094002-20b53e00-b299-11e9-8b5b-8ac605918251.jpg)

**Comment by n8fr8** [comment] 2019-07-31 19:28
Closing this for now, until we have reports from users!

**Closed by n8fr8** 2019-07-31 19:28 UTC
Labels: bug
