### ISSUE TITLE
App Settings

### ISSUE THREAD

**Issue by cstiens** [OpenArchive/openarchive-ios#95] opened 2019-04-25 15:43 UTC
@n8fr8 On Android we have Enable ProofMode, Enable Onion Routing and Upload on Wifi Only. On iOS, I suppose we would only have Upload on Wifi Only. 

Are there any other settings we need right now?

**Comment by kckthx** [comment] 2019-04-25 21:36
I know we've been round and round about the name of the settings screen, but I think we've finally landed on what works. 

Here is the new layout for 'Menu' with a division between server specific and global settings.
![OA-Menu](https://user-images.githubusercontent.com/36669955/56769716-a5af2980-6777-11e9-8940-19b1ee8ef65b.png)

The 'Data Usage' tab will take you to a place to select whether or not to upload only over wifi #89 . This will also be an option in initial onboarding, but we haven't gotten to designing all of that yet. 
![OA-data-usage](https://user-images.githubusercontent.com/36669955/56769735-b790cc80-6777-11e9-9938-56e4ca652917.png)

@cstiens @tladesignz @n8fr8 @foundscapes

**Comment by tladesignz** [comment] 2019-04-29 13:37
Duplicate of #96. I close this, please continue there, if need be.

**Closed by tladesignz** 2019-04-29 13:37 UTC
Labels: duplicate
